### PR TITLE
qvm-template: load all repo files from /etc/qubes/repo-templates

### LINKED ISSUE #7354: qvm-template loads only a single .repo file from /etc/qubes/repo-templates/
[How to file a helpful issue](https://www.qubes-os.org/doc/issue-tracking/)

### Qubes OS release

R4.1

### Brief summary

`qvm-template` should load all .repo files from `/etc/qubes/repo-templates`, but loads only a single one.

### Steps to reproduce

1. Add additional .repo file into `/etc/qubes/repo-templates`
2. Try to install a template from ther

### Expected behavior

Template is installed.

### Actual behavior

Template not found.

### PR DESCRIPTION
**Pull request by marmarek**
Use *.repo glob, instead of hardcoded repo-templates.repo file name.

Fixes QubesOS/qubes-issues#7354

### CODE REVIEW

**Comment by marmarek** [comment]
PipelineRetry

**Comment by marmarek** [comment]
PipelineRetry

**Comment by marmarek** [comment]
PipelineRetry

**Comment by marmarek** [comment]
PipelineRetry

**Comment by fepitre** [comment]
PipelineRetry

**Comment by fepitre** [comment]
PipelineRetry

**Comment by fepitre** [comment]
PipelineRetry

**Comment by fepitre** [comment]
PipelineRetry

**Comment by fepitre** [comment]
PipelineRetry

**Pull request merged**
