### PR TITLE
Document that qvm-volume revert can revert to a specific revision

### PR DESCRIPTION
**Pull request by Rudd-O**

### CODE REVIEW

**Comment by Rudd-O** [comment]
Uh the codesigning thing says "no valid key found" even though the commit is verified according to Github.

**Comment by Rudd-O** [comment]
image

**Comment by Rudd-O** [comment]
Sometimes Github is just an asshole.

**Comment by marmarek** [comment]
Those 4 commits also want squashing into one.

**Comment by Rudd-O** [comment]
Will do right away.  Thanks.

**Review by marmarek — APPROVED** [review]

**Pull request merged**
