### PR TITLE
Add events_max_delay setting for qubes-gui-daemon

### PR DESCRIPTION
**Pull request by ArrayBolt3**
Allows gubes-gui-daemon X event buffering delay to be configured. Prerequisite for https://github.com/QubesOS/qubes-gui-daemon/pull/149

### CODE REVIEW

**Comment by ArrayBolt3** [comment]
Renamed xbuf to ebuf in https://github.com/QubesOS/qubes-gui-daemon/pull/149, thus the name change has been propagated to here as well.

**Comment by ArrayBolt3** [comment]
Renamed to `events_max_delay` in https://github.com/QubesOS/qubes-gui-daemon/pull/149#issuecomment-2424613566, thus changing the name here once again.

**Comment by ArrayBolt3** [comment]
Rebased onto the tip of main. Did two force pushes because I forgot to sign my commit the first time.

**Comment by ArrayBolt3** [comment]
Updated to work with the new changes from commit 53f7b09.

**Review by marmarek — APPROVED** [review]

**Pull request merged**
